# Generated by Django 3.1.7 on 2021-05-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210525_1522'),
        ('movies', '0002_auto_20210525_1543'),
    ]

    operations = [
    ]
