# Generated by Django 3.1.7 on 2021-05-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
